# -*- coding: utf-8 -*-
"""Script_to_Voice.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cjRbwtBptGX2f4M07mDYIlpPxe1h78j_
"""

!pip install moviepy gTTS
!apt-get update && apt-get install -y imagemagick

from google.colab import files
uploaded = files.upload()

from moviepy.editor import *
from gtts import gTTS
import os
import time

# === STEP 1: SCRIPT ===
script_text = "In a magical candy forest, a brave little penguin in a red scarf began his sweetest adventure ever."

# === STEP 2: AUDIO FILE GENERATION ===
audio_path = "narration.mp3"  # gTTS uses MP3
try:
    tts = gTTS(text=script_text, lang='en')
    tts.save(audio_path)
    time.sleep(1)
    if not os.path.exists(audio_path):
        raise FileNotFoundError(f"Audio file {audio_path} was not created.")
except Exception as e:
    print(f"Error generating audio: {e}")
    exit(1)

# === STEP 3: SUBTITLE FILE ===
subtitle_path = "subtitles.srt"
try:
    with open(subtitle_path, "w") as f:
        f.write("1\n00:00:00,000 --> 00:00:10,000\n" + script_text + "\n")
    if not os.path.exists(subtitle_path):
        raise FileNotFoundError(f"Subtitle file {subtitle_path} was not created.")
except Exception as e:
    print(f"Error creating subtitle file: {e}")
    exit(1)

# === STEP 4: CREATE VIDEO FROM IMAGE ===
image_path = "penguin.png"  # Update with the uploaded file name
video_duration = 10

try:
    if not os.path.exists(image_path):
        raise FileNotFoundError(f"Image file {image_path} does not exist.")
    image_clip = ImageClip(image_path).set_duration(video_duration)
    audio_clip = AudioFileClip(audio_path)
    image_clip = image_clip.set_audio(audio_clip)

    # === STEP 4.1: CREATE SUBTITLES MANUALLY ===
    def parse_srt(file_path):
        subtitles = []
        with open(file_path, 'r') as f:
            lines = f.read().splitlines()
            i = 0
            while i < len(lines):
                if lines[i].isdigit():
                    time_line = lines[i + 1]
                    start_end = time_line.split(' --> ')
                    start = parse_time(start_end[0])
                    end = parse_time(start_end[1])
                    text = lines[i + 2]
                    subtitles.append((start, end, text))
                    i += 4
                else:
                    i += 1
        return subtitles

    def parse_time(time_str):
        h, m, s_ms = time_str.split(':')
        s, ms = s_ms.split(',')
        return int(h) * 3600 + int(m) * 60 + int(s) + int(ms) / 1000

    subtitle_clips = []
    for start, end, text in parse_srt(subtitle_path):
        text_clip = (TextClip(text, font='DejaVu-Sans', fontsize=24, color='white', bg_color='black', stroke_color='black', stroke_width=1)
                     .set_position(('center', 'bottom'))
                     .set_start(start)
                     .set_end(end))
        subtitle_clips.append(text_clip)

    final_video = CompositeVideoClip([image_clip] + subtitle_clips)
    output_video = "final_penguin_adventure.mp4"
    final_video.write_videofile(output_video, fps=24, codec='libx264', audio_codec='aac')
    print("✅ Video created successfully:", output_video)

    # Download the video
    from google.colab import files
    files.download(output_video)

except Exception as e:
    print(f"Error creating video: {e}")
finally:
    try:
        if 'final_video' in locals():
            final_video.close()
        if 'image_clip' in locals():
            image_clip.close()
        if 'audio_clip' in locals():
            audio_clip.close()
        for clip in subtitle_clips:
            clip.close()
    except Exception as e:
        print(f"Error closing resources: {e}")

!pip install moviepy gTTS
!apt-get update && apt-get install -y imagemagick
!sed -i '/<policy domain="path" rights="none" pattern="@\*"/d' /etc/ImageMagick-6/policy.xml

from google.colab import files
uploaded = files.upload()